characterization:
  single_qubit:
    0:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 4244
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9159136546184738
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4208776000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: 0.8658972638027499
      mean_exc_states:
      - 0.00020598830523433612
      - -0.000861103746100012
      mean_gnd_states:
      - -0.0001513688112477938
      - -0.000441028491152557
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0.3182
      readout_fidelity: 0.8318273092369478
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.0005085202588816099
    1:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 2341
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.8660475234270415
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4512588000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: -0.32168316452488965
      mean_exc_states:
      - 0.0007102089937903116
      - -0.0002702066086478183
      mean_gnd_states:
      - 0.0002642963054069388
      - -0.000418810783304585
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.732095046854083
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.00037240875980937483
    2:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 3730
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9080488621151273
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4852651000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: -2.1393601839513283
      mean_exc_states:
      - -0.0008111267738271113
      - 0.0020824197916813657
      mean_gnd_states:
      - -0.00017062783813450084
      - 0.0010799865735753509
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.8160977242302544
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.001490149380573375
  two_qubit:
    0-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-0:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-2:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    2-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
instruments:
  qcm_rf0:
    o1:
      attenuation: 16
      lo_frequency: 3900000000.0
    o2:
      attenuation: 20
      lo_frequency: 4350000000.0
  qrm_rf0:
    i1:
      acquisition_duration: 2100
      acquisition_hold_off: 400
    o1:
      attenuation: 48
      lo_frequency: 7250000000.0
  qrm_rf1:
    i1:
      acquisition_duration: 2104
      acquisition_hold_off: 400
    o1:
      attenuation: 16
      lo_frequency: 4650000000.0
native_gates:
  single_qubit:
    0:
      MZ:
        amplitude: 0.12
        duration: 1900
        frequency: 6869847000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.322
        duration: 40
        frequency: 4208850000.0
        phase: 0
        relative_start: 0
        shape: Drag(5,0.173)
        type: qd
    1:
      MZ:
        amplitude: 0.47
        duration: 2300
        frequency: 6964272000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.2615
        duration: 40
        frequency: 4512400000.0
        phase: 0
        relative_start: 0
        shape: Drag(5,-0.772)
        type: qd
    2:
      MZ:
        amplitude: 0.18
        duration: 1900
        frequency: 7072050000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.16
        duration: 40
        frequency: 4854290000.0
        phase: 0
        relative_start: 0
        shape: Drag(5,1.085)
        type: qd
nqubits: 3
qubits:
- 0
- 1
- 2
settings:
  nshots: 4095
  relaxation_time: 200000
topology:
- - 0
  - 1
- - 1
  - 2
