characterization:
  single_qubit:
    0:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 4244
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.8801874163319947
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4208776000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: 2.0751321638066647
      mean_exc_states:
      - -0.0006958708960577678
      - -0.0005633016024364516
      mean_gnd_states:
      - -0.00044833833945192236
      - -0.00011482897776831905
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.7603748326639893
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.0005704693449101313
    1:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 2341
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.8923192771084337
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4512588000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: 1.4692461255111506
      mean_exc_states:
      - -0.0005015995589588437
      - -0.001417389702107568
      mean_gnd_states:
      - -0.0005771314376186045
      - -0.0006761596540699516
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.7846385542168675
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.0009143441512213916
    2:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 3730
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9473728246318607
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4852651000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: -2.387
      mean_exc_states:
      - -0.001285639349451214
      - 0.001549459783442515
      mean_gnd_states:
      - -0.0006348645445883144
      - 0.0009657521189344145
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.8947456492637215
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.00148
  two_qubit:
    0-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-0:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-2:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    2-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
instruments:
  qcm_rf0:
    o1:
      attenuation: 16
      lo_frequency: 3900000000.0
    o2:
      attenuation: 20
      lo_frequency: 4350000000.0
  qrm_rf0:
    i1:
      acquisition_duration: 2500
      acquisition_hold_off: 400
    o1:
      attenuation: 48
      lo_frequency: 7250000000.0
  qrm_rf1:
    i1:
      acquisition_duration: 2104
      acquisition_hold_off: 400
    o1:
      attenuation: 16
      lo_frequency: 5030000000.0
native_gates:
  single_qubit:
    0:
      MZ:
        amplitude: 0.12
        duration: 2000
        frequency: 6869797000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.332
        duration: 40
        frequency: 4208698301
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
    1:
      MZ:
        amplitude: 0.05
        duration: 2000
        frequency: 6964322000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.279
        duration: 40
        frequency: 4512411524.0
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
    2:
      MZ:
        amplitude: 0.05
        duration: 2000
        frequency: 7072350000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.168
        duration: 40
        frequency: 4854359444
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
nqubits: 3
qubits:
- 0
- 1
- 2
settings:
  nshots: 4095
  relaxation_time: 100000
topology:
- - 0
  - 1
- - 1
  - 2
