characterization:
  single_qubit:
    0:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 4244
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9226070950468541
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4208850000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: 1.2463124536006933
      mean_exc_states:
      - -0.0004239731274879679
      - -0.0011779058098539746
      mean_gnd_states:
      - -0.0006216959617310039
      - -0.0005900977603866887
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0.3182
      readout_fidelity: 0.8452141900937082
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.000652510782939115
    1:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 2341
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9247824631860777
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4512588000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: 2.18461069261048
      mean_exc_states:
      - -0.0015152952225773277
      - -0.0007579803826934519
      mean_gnd_states:
      - -0.0009852207448395084
      - -5.687345725290662e-06
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.8495649263721553
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.0009547860231226295
    2:
      Ec: 0.0
      Ej: 0.0
      T1: 0
      T2: 3730
      T2_spin_echo: 0
      anharmonicity: 0
      assignment_fidelity: 0.9080488621151273
      asymmetry: 0.0
      bare_resonator_frequency: 0
      drive_frequency: 4852651000.0
      effective_temperature: 0.0
      g: 0.0
      iq_angle: -2.1393601839513283
      mean_exc_states:
      - -0.0008111267738271113
      - 0.0020824197916813657
      mean_gnd_states:
      - -0.00017062783813450084
      - 0.0010799865735753509
      mixer_drive_g: 0.0
      mixer_drive_phi: 0.0
      mixer_readout_g: 0.0
      mixer_readout_phi: 0.0
      peak_voltage: 0
      pi_pulse_amplitude: 0
      readout_fidelity: 0.8160977242302544
      readout_frequency: 0
      state0_voltage: 0
      state1_voltage: 0
      sweetspot: 0.0
      threshold: 0.001490149380573375
  two_qubit:
    0-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-0:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    1-2:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
    2-1:
      cz_fidelity: 0.0
      gate_fidelity: 0.0
instruments:
  qcm_rf0:
    o1:
      attenuation: 20
      lo_frequency: 4800000000.0
    o2:
      attenuation: 20
      lo_frequency: 5100000000.0
  qrm_rf0:
    i1:
      acquisition_duration: 2000
      acquisition_hold_off: 440
    o1:
      attenuation: 60
      lo_frequency: 6820000000.0
  qrm_rf1:
    i1:
      acquisition_duration: 2104
      acquisition_hold_off: 400
    o1:
      attenuation: 20
      lo_frequency: 5500000000.0
native_gates:
  single_qubit:
    0:
      MZ:
        amplitude: 0.5
        duration: 2000
        frequency: 6505375000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.217
        duration: 40
        frequency: 4719586000.0
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
    1:
      MZ:
        amplitude: 0.3
        duration: 2000
        frequency: 6601464000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.166
        duration: 40
        frequency: 4997700000.0
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
    2:
      MZ:
        amplitude: 0.075
        duration: 2000
        frequency: 6702978000.0
        phase: 0
        relative_start: 0
        shape: Rectangular()
        type: ro
      RX:
        amplitude: 0.168
        duration: 40
        frequency: 5391250000.0
        phase: 0
        relative_start: 0
        shape: Gaussian(5)
        type: qd
  two_qubit:
    0-1:
      CZ:
      - amplitude: 0.31605
        duration: 700
        frequency: 4208850000.0
        phase: 0
        qubit: 1
        relative_start: 0
        shape: Gaussian(5)
        type: qd
nqubits: 3
qubits:
- 0
- 1
- 2
settings:
  nshots: 4095
  relaxation_time: 200000
topology:
- - 0
  - 1
- - 1
  - 2
