name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install qibolab
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install qibolab[qblox,zh,qm,rfsoc]
      - name: Test platforms
        run: |
          export QIBOLAB_PLATFORMS=$(realpath .)
          pytest
