name: Test platform creation
on: push
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        version: ["main", "stable"]
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install qibolab stable
        if: ${{ matrix.version == 'stable' }}
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install pytest
          pip install qcodes qibolab-qm qibolab-qblox
      - name: Install qibolab main
        if: ${{ matrix.version == 'main' }}
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install pytest
          for lib in qibolab-qm qibolab-qblox qibolab
          do
            pip install git+https://github.com/qiboteam/$lib
          done
      - name: Test platforms
        run: |
          source testenv/bin/activate
          QIBOLAB_PLATFORMS=$(realpath .) pytest _tests/
